version: '3'
services:
  zookeeper:
    image: debezium/zookeeper:1.5
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:1.5
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  postgres:
    image: debezium/postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ${PWD}/postgres:/docker-entrypoint-initdb.d
  connect:
    image: debezium/connect:1.5
    ports:
      - 8083:8083
    links:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=test-consumer-group
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  flink-base-img:
    build:
      context: ./client-image
      dockerfile: Dockerfile.base
    image: whyuenac/flink-base:java8-3.2.3-1.14.0_1
    command: echo image build success!
    
  sql-client:
    build: ./client-image
    image: egnarts/flink-sql-client
    depends_on:
      - kafka
      - jobmanager
      - elasticsearch
    environment:
      FLINK_JOBMANAGER_HOST: jobmanager
      ZOOKEEPER_CONNECT: zookeeper
      KAFKA_BOOTSTRAP: kafka
      ES_HOST: elasticsearch
      # HOODIE_ENV_fs_DOT_oss_DOT_endpoint: "minio:9000"
      # HOODIE_ENV_fs_DOT_oss_DOT_accessKeyId: abc
      # HOODIE_ENV_fs_DOT_oss_DOT_accessKeySecret: xyzxyzxyz
      # HOODIE_ENV_fs_DOT_oss_DOT_impl: org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/ckp:/ckp
  jobmanager:
    image: whyuenac/flink-base:java8-3.2.3-1.14.0_1
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 50
        parallelism.default: 1
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/ckp:/ckp
  taskmanager:
    image: whyuenac/flink-base:java8-3.2.3-1.14.0_1
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 50
        parallelism.default: 1
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/ckp:/ckp
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    ports:
      - "5601:5601"
  # minio:
  #   image: minio/minio
  #   env_file:
  #     - .env
  #   ports:
  #     - "9000:9000"
  #   command: server /data
